[project]
name = "bomb-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["pygame-ce>=2.5.6"]

[dependency-groups]
dev = ["pytest>=9.0.2"]
